Poisson dist metrics for #146 and #11
tidymodels/yardstick pull request #230
Opened 2021-07-28 15:48 UTC by topepo

New items were added for counts in `helper-data.R` and `examples-counts.R`. 

Log-loss and a [deviance](https://en.wikipedia.org/wiki/Deviance_(statistics)) metric were added.

2021-07-28 21:05 UTC, DavisVaughan requested changes

2021-08-03 17:55 UTC, topepo commented
I've played around with this for a few days. I have yet to find a case where they are not 99% correlated. I'll remove the deviance metric so that we can avoid the confusion.

2021-08-03 17:57 UTC, topepo commented on R/num-poisson_log_loss.R
> +#' Calculate the loss function for the Poisson distribution.
Shall I add an `as.integer()` coercion to `poisson_log_loss_vec()`?

2021-08-03 18:47 UTC, DavisVaughan commented on R/num-poisson_log_loss.R
> +#' Calculate the loss function for the Poisson distribution.
You could also do `vctrs::vec_cast(x, integer())` which would allow `1 -> 1L` but would error on `1.5 -> error`

2021-08-03 20:30 UTC, DavisVaughan commented on NEWS.md
> +* `poisson_log_loss()` and `poisson_deviance()` were added (#146).
```suggestion
* New metric `poisson_log_loss()` was added (#146).
```

2021-08-03 20:32 UTC, DavisVaughan commented on tests/testthat/test-num-poisson_log_loss.R
> +count_poor    <- data_counts()$poor
Can you please put these inside the `test_that()` block so they don't persist between files?

2021-08-16 13:49 UTC, merged